exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/remoboard/remoboard.github.io"
  
title: Remoboard
description: Remote Keyboard | 远程输入法 | Type From PC/Mac Desktop, Make Typing on Phone Faster. 通过电脑给手机打字，让打字飞速。
